name: tag

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: 'version tag (vx.x.x)'
        required: true

jobs:
  tag_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Push git tag
      run: |
        echo ${{ sender }}
        git tag -a ${{ inputs.tag }} -m ${{ inputs.tag }}
        git push origin ${{ inputs.tag }}
