name: tag

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: 'version tag (vx.x.x)'
        required: true
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  tag_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Push git tag
      run: |
        curl -s -X POST "https://api.github.com/repos/${{github.repository}}/git/refs" \
        -H "Authorization: token $GITHUB_TOKEN" \
        -d @- << EOS
        {
          "ref": "refs/tags/${{inputs.tag}}",
          "sha": "${{github.sha}}"
        }
        EOS
